puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Nicole Pell"
puts "Bernard Mordan"
puts "Elena Garrone"
puts "Yvette Cook"
puts "Stephen Giles"
puts "Ana Nogal"
puts "Tim Scully"
puts "Ella Fay"
puts "Fadie H"
puts "Dan Cutler"
puts "Camilla van Klinken"
puts "James Carter"
puts "Andrew Hercules"
puts "Karin Nielsen"
puts "Andrew Snead"
puts "Rachel Nolan"
puts "Anna Schechter"
puts "Alex Fakhri"
puts "Denise Yu"
puts "Andrew Harrison"
puts "Sandrine"
puts "Craig H" 
puts "Vic"
puts "Pablo"
puts "-------------"
print "Overall, we have "
print 23
puts " great students"
